let filmes = [
    "Matrix",
    "Blade Runner: O Caçador de Androids",
    "2001: Uma Odisséia no Espaço",
    "Gravidade",
    "Brilho Eterno de uma Mente sem lembranças",
    "A Origem",
    "Cidade das Sombras",
    "Fonte da Vida",
    "Os 12 macacos",
    "Filhos da Esperança",
    "Inimigo Meu",
    "O Exterminador do Futuro 2: O Julgamento Final",
    "O Segredo do Abismo",
    "Aliens: O Resgate",
    "Avatar",
    "Alien: O Oitavo Passageiro",
    "Star Wars, Episódio V: O Império Contra-Ataca",
    "Star Wars, Episódio III: A Vingança dos Sith",
    "De Volta Para o Futuro",
    "Contato",
    "Gattaca, uma Experiência Genética",
    "O Dia Em Que A Terra Parou",
    "O Incrível Homem Que Encolheu",
    "Minority Report: A Nova Lei",
    "A.I. Inteligência Artificial",
    "E.T.: O Extraterrestre",
    "Efeito Borboleta",
    "Vanilla Sky",
    "Contra o Tempo",
    "Donnie Darko",
    "V de Vingança",
    "Brazil, o Filme",
    "1984",
    "Distrito 9",
    "O Vingador do Futuro",
    "Star Trek",
    "O Predador",
    "Eu Sou a Lenda",
    "A Ilha",
    "Eu, Robô",
    "13º Andar",
    "K-Pax: O Caminho da Luz",
    "Energia Pura",
    "O Homem que caiu na Terra",
    "Starman: O Homem das Estrelas",
    "Cocoon",
    "Duna",
    "Cubo",
    "Prova Final"
]

module.exports = {
    filmes
}